name: doomsday

instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: doomsday
    properties:
      backends:
      - name: tooling-credhub
        properties:
          address: ((tooling_bosh.target))
          auth:
            client_id: ((tooling_bosh.client_id))
            client_secret: ((tooling_bosh.client_secret))
            grant_type: client_credentials
          insecure_skip_verify: true # needed because the bosh cert isn't part of the trust store.
        type: credhub
        refresh_internal: 1
      - name: tooling-bosh-tls
        properties:
          hosts: ((tooling_bosh.hosts))
        type: tlsclient
        refresh_internal: 1
      notifications:
        backend:
          properties:
            notify_ok: false
            webhook: ((slack_webhook_url))
          type: slack
        doomsday_url: "https://doomsday.((/domain))"
        schedule:
          properties:
            interval: 360
          type: constant
      server:
        auth:
          type: none
        port: 80
    release: doomsday
  - name: bosh-dns-aliases
    release: bosh-dns-aliases
    properties:
      aliases:
      - domain: opsuaa.internal
        targets:
        - deployment: opsuaa
          domain: bosh
          instance_group: opsuaa
          network: opsuaa
          query: '*'
  name: doomsday
  networks:
  - name: production-monitoring
  persistent_disk_type: 5GB
  stemcell: default
  vm_type: t3.medium
  vm_extensions:
  - production-doomsday-lb

releases:
- name:    doomsday
  version: 0.9.2
  url:     https://github.com/doomsday-project/doomsday-boshrelease/releases/download/v0.9.2/doomsday-0.9.2.tgz
  sha1:    e17a5ee70875a19926f80879e8baf9ac3244c981
- name: bosh-dns-aliases
  version: latest

stemcells:
- alias: default
  os: ubuntu-jammy
  version: latest

update:
  canaries: 1
  canary_watch_time: 30000-600000
  max_in_flight: 1
  serial: true
  update_watch_time: 30000-600000
