name: doomsday

instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: doomsday
    properties:
      backends:
      - name: master
        properties:
          address: ((master.address))
          auth:
            client_id: ((master.client))
            client_secret: ((master.client-secret))
            grant_type: client_credentials
          insecure_skip_verify: true # needed because the bosh cert isn't part of the trust store.
        type: credhub
        refresh_internal: 1
      - name: tooling
        properties:
          address: ((tooling.address))
          auth:
            client_id: ((tooling.client))
            client_secret: ((tooling.client-secret))
            grant_type: client_credentials
          insecure_skip_verify: true # needed because the bosh cert isn't part of the trust store.
        type: credhub
        refresh_internal: 1
      - name: development
        properties:
          address: ((dev.address))
          auth:
            client_id: ((dev.client))
            client_secret: ((dev.client-secret))
            grant_type: client_credentials
          insecure_skip_verify: true # needed because the bosh cert isn't part of the trust store.
        type: credhub
        refresh_internal: 1
      - name: credhub-staging
        properties:
          address: ((credhub-staging.address))
          auth:
            client_id: ((credhub-staging.client))
            client_secret: ((credhub-staging.client-secret))
            grant_type: client_credentials
          insecure_skip_verify: true # needed because the bosh cert isn't part of the trust store.
        type: credhub
        refresh_internal: 1
      - name: staging
        properties:
          address: ((staging.address))
          auth:
            client_id: ((staging.client))
            client_secret: ((staging.client-secret))
            grant_type: client_credentials
          insecure_skip_verify: true # needed because the bosh cert isn't part of the trust store.
        type: credhub
        refresh_internal: 1
      - name: production
        properties:
          address: ((prod.address))
          auth:
            client_id: ((prod.client))
            client_secret: ((prod.client-secret))
            grant_type: client_credentials
          insecure_skip_verify: true # needed because the bosh cert isn't part of the trust store.
        type: credhub
        refresh_internal: 1
      - name: masterbosh
        properties:
          hosts: ((master.hosts))
        type: tlsclient
        refresh_internal: 1
      - name: prod-urls
        properties:
          hosts: ((prod.hosts))
        type: tlsclient
        refresh_internal: 1
      notifications:
        backend:
          properties:
            notify_ok: false
            webhook: ((slack-webhook))
          type: slack
        doomsday_url: "https://doomsday.fr.cloud.gov"
        schedule:
          properties:
            interval: 360
          type: constant
      server:
        auth:
          type: none
        port: 80
    release: doomsday
  - name: bosh-dns-aliases
    release: bosh-dns-aliases
    properties:
      aliases:
      - domain: opsuaa.internal
        targets:
        - deployment: opsuaa
          domain: bosh
          instance_group: opsuaa
          network: opsuaa
          query: '*'
  name: doomsday
  networks:
  - name: production-monitoring
  persistent_disk_type: 5GB
  stemcell: default
  vm_type: t3.medium
  vm_extensions:
  - production-doomsday-lb

releases:
- name:    doomsday
  version: 0.9.2
  url:     https://github.com/doomsday-project/doomsday-boshrelease/releases/download/v0.9.2/doomsday-0.9.2.tgz
  sha1:    e17a5ee70875a19926f80879e8baf9ac3244c981
- name: bosh-dns-aliases
  version: latest

stemcells:
- alias: default
  os: ubuntu-jammy
  version: latest

update:
  canaries: 1
  canary_watch_time: 30000-600000
  max_in_flight: 1
  serial: true
  update_watch_time: 30000-600000
